### ISSUE TITLE
Some items only have url and nothing else

### ISSUE THREAD

**Issue by zpelechova** [dtrungtin/actor-imdb-scraper#16]
![image](https://user-images.githubusercontent.com/39551460/118781640-9256e580-b88d-11eb-98e1-f2ac68b21abc.png)
https://my.apify.com/view/runs/Gwh5eGIGV9ITy71fn

**Comment by zpelechova** [comment]
Still : https://api.apify.com/v2/datasets/q5iMWUFv4q3TdQOdT/items?clean=true&format=json

**Comment by dtrungtin** [comment]
It seems it's related to proxy. Fixed by set proxy with country US.

**Comment by zpelechova** [comment]
wrote it and didnt post it :( 
(but seems it is not the only problem)
Seems it is with films/series not yet screened. Lets first just add check if there is title, put it in dataset and if not, skip it 
And step too - make sure also future films/series are scraped (feel free to create a n
ew issue for it)

**Comment by zpelechova** [comment]
Not fixed: https://my.apify.com/view/runs/LHRejTpLd6tYbatSs

**Comment by dtrungtin** [comment]
) Lets first just add check if there is title, put it in dataset and if not, skip it.
Updated.

**Comment by zpelechova** [comment]
Still not working: 
https://api.apify.com/v2/datasets/98ch68f6ee0jqSKDK/items?clean=true&format=json
https://my.apify.com/view/runs/ybG3OCA9IeArSqEu8

**Comment by dtrungtin** [comment]
Fixed.

**Comment by zpelechova** [comment]
Still not working: https://my.apify.com/view/runs/8H3aHMai9BpN31YIG

**Comment by dtrungtin** [comment]
Please use the latest build.

**Comment by zpelechova** [comment]
Fixed 07/2021
